name: Build Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Extension release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Stamp Version
        run: |
          cat package.json | jq --arg VER "${{ github.event.inputs.release_version }}" '.version=$VER' > /tmp/package.json 
          cp /tmp/package.json ./package.json
          npm ci
          npm run vscode:prepublish

      - name: Package
        uses: lannonbr/vsce-action@0f3391ee0477b08fae949eb0a875e91e6d20b075
        with:
          args: "package"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-${{ github.event.inputs.release_version }}-zen.vsix
          path: ./go-${{ github.event.inputs.release_version }}.vsix
          if-no-files-found: error