name: Build Release (Windows)
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Extension release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Package VSCGO
        run: |
          go build -ldflags '-s -w'
          mv vscgo.exe ..
        working-directory: 'vscgo'

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-${{ github.event.inputs.release_version }}-zen-win
          path: ./vscgo.exe
          if-no-files-found: error
